# Joints limits
#
# Sources:
#
#  - UR10 User Manual, Universal Robots, UR10/CB3, Version 3.13
#    https://s3-eu-west-1.amazonaws.com/ur-support-site/69442/99203_UR10_User_Manual_en_Global.pdf
#  - Support > Articles > UR articles > Max. joint torques
#    https://www.universal-robots.com/articles/ur-articles/max-joint-torques
#    retrieved: 2020-06-16, last modified: 2020-06-09
# Corrected Joint Limits for Giskard
joint_limits:
  shoulder_pan_joint:
    has_position_limits: true
    min_position: -6.28318530718   # -360 deg in rad
    max_position: 6.28318530718    # 360 deg in rad
    has_velocity_limits: true
    max_velocity: 2.09439510239    # 120 deg/s in rad/s
    has_acceleration_limits: true
    max_acceleration: 5.0          # rad/s^2
    has_effort_limits: true
    max_effort: 330.0

  shoulder_lift_joint:
    has_position_limits: true
    min_position: -6.28318530718
    max_position: 6.28318530718
    has_velocity_limits: true
    max_velocity: 2.09439510239
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_effort_limits: true
    max_effort: 330.0

  elbow_joint:
    has_position_limits: true
    min_position: -3.14159265359   # -180 deg in rad
    max_position: 3.14159265359    # 180 deg in rad
    has_velocity_limits: true
    max_velocity: 3.14159265359    # 180 deg/s in rad/s
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_effort_limits: true
    max_effort: 150.0

  wrist_1_joint:
    has_position_limits: true
    min_position: -6.28318530718
    max_position: 6.28318530718
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_effort_limits: true
    max_effort: 56.0

  wrist_2_joint:
    has_position_limits: true
    min_position: -6.28318530718
    max_position: 6.28318530718
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_effort_limits: true
    max_effort: 56.0

  wrist_3_joint:
    has_position_limits: true
    min_position: -6.28318530718
    max_position: 6.28318530718
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_effort_limits: true
    max_effort: 56.0

