# Joints limits
#
# Sources:
#
#  - Universal Robots e-Series, User Manual, UR10e, Version 5.8
#    https://s3-eu-west-1.amazonaws.com/ur-support-site/69139/99405_UR10e_User_Manual_en_Global.pdf
#  - Support > Articles > UR articles > Max. joint torques
#    https://www.universal-robots.com/articles/ur-articles/max-joint-torques
#    retrieved: 2020-06-16, last modified: 2020-06-09
# Joints limits (converted to radians)
joint_limits:
  shoulder_pan_joint:
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 330.0
    max_position: 6.28319      # 360°
    max_velocity: 2.0944       # 120°/s
    min_position: -6.28319     # -360°
  shoulder_lift_joint:
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 330.0
    max_position: 6.28319
    max_velocity: 2.0944
    min_position: -6.28319
  elbow_joint:
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 150.0
    max_position: 3.14159      # 180°
    max_velocity: 3.14159      # 180°/s
    min_position: -3.14159
  wrist_1_joint:
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 54.0
    max_position: 6.28319
    max_velocity: 3.14159
    min_position: -6.28319
  wrist_2_joint:
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 54.0
    max_position: 6.28319
    max_velocity: 3.14159
    min_position: -6.28319
  wrist_3_joint:
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 54.0
    max_position: 6.28319
    max_velocity: 3.14159
    min_position: -6.28319
